// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBa416EGwYo86kRRR2XpWLfenZQ9tQE5W8',
    appId: '1:869089978216:web:f91c2139fe64e7a14dd8dd',
    messagingSenderId: '869089978216',
    projectId: 'chat-app-tharwat-655da',
    authDomain: 'chat-app-tharwat-655da.firebaseapp.com',
    storageBucket: 'chat-app-tharwat-655da.appspot.com',
    measurementId: 'G-WTL1FL3BPG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3WXyIT_P0wUk-IrWuOWAKwakAisoiF94',
    appId: '1:869089978216:android:73f261cda6ff29374dd8dd',
    messagingSenderId: '869089978216',
    projectId: 'chat-app-tharwat-655da',
    storageBucket: 'chat-app-tharwat-655da.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVNqDVSc10cC7ABsXPWcLSaqhbTMYNF_s',
    appId: '1:869089978216:ios:3b29f757d8423ed54dd8dd',
    messagingSenderId: '869089978216',
    projectId: 'chat-app-tharwat-655da',
    storageBucket: 'chat-app-tharwat-655da.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVNqDVSc10cC7ABsXPWcLSaqhbTMYNF_s',
    appId: '1:869089978216:ios:d5b87b6ee291e5794dd8dd',
    messagingSenderId: '869089978216',
    projectId: 'chat-app-tharwat-655da',
    storageBucket: 'chat-app-tharwat-655da.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
